import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Link from 'next/link'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav>
          <Link href="/slider">Slider</Link>
          <Link href="/mediabutton">Media Button</Link>
          <Link href="/mediabutton2">Media Button 2</Link>
          <Link href="/mediabutton3">Media Button 3</Link>
          <Link href="/mediabutton4">Media Button 4</Link>
          <Link href="/location-pad">Location Pad</Link>
          <Link href="/location-pad2">Location Pad 2</Link>
          <Link href="/location-pad3">Location Pad 3</Link>
          <Link href="/private-chat">Private Chat</Link>
          <Link href="/layout-editor">Layout Editor</Link>
          <Link href="/layout-editor2">Layout Editor 2</Link>
        </nav>
        <div className="content">{children}</div>
      </body>
    </html>
  )
}
